version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Docker/Volumes/MongoDB:/data/db
    networks:
      - cep-backend-network
  node:
    image: node
    build: .
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9090:9090"
    environment:
      - PORT=${PORT}
      - STRING_CONNECTION_DB=${STRING_CONNECTION_DB}
    depends_on:
      - mongo
    networks:
      - cep-backend-network

networks:
  cep-backend-network:
    driver: bridge
