version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
