name: Build workflow

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: Build
    steps:
      - uses: actions/checkout@v2
      - run: npm ci