name: Deploy workflow

on:
  workflow_call:
    secrets:
      IMAGE_NAME:
        required: true
      PROJECT_ID:
        required: true
      GCR_EMAIL_ACCOUNT:
        required: true
      GCR_DEVOPS_SERVICE_ACCOUNT_KEY:
        required: true
      REGION:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: Deploy
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCR_EMAIL_ACCOUNT }}
          service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
      - run: |
          gcloud auth configure-docker
      - run: |-
          docker build -t $IMAGE_NAME:$GITHUB_SHA .
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      - run: docker tag $IMAGE_NAME:$GITHUB_SHA gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
      - run: |-
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
      - run: |-
          gcloud config set project $PROJECT_ID
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
      - run: |-
          gcloud run deploy $IMAGE_NAME --image gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA --region $REGION
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          REGION: ${{ secrets.REGION }}