name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f docker-compose.yml up -d mongo
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - uses: actions/checkout@v2
    - name: Stop containers
      run: docker-compose -f docker-compose.yml down
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCR_EMAIL_ACCOUNT }}
        service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - run: |
        gcloud auth configure-docker
    - name: Image
      run: |-
        docker build -t cep-backend:latest .
    - name: Tag
      run: |-
        docker tag cep-backend:latest gcr.io/${{ secrets.PROJECT_ID }}/cep-backend:latest
    - name: Build
      run: |-
        docker push gcr.io/${{ secrets.PROJECT_ID }}/cep-backend:latest
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply -auto-approve
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCR_EMAIL_ACCOUNT }}
        service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - name: Config project
      run: |-
          gcloud config set project ${{ secrets.PROJECT_ID }}
    - name: Config zone
      run: |-
          gcloud config set zone ${{ secrets.ZONE }}
    - name: Update Image
      run: |-
        gcloud compute instances update-container vm-instance 
        --metadata startup-script=teste --container-image gcr.io/${{ secrets.PROJECT_ID }}/cep-backend:latest
