name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Start containers
    - uses: actions/checkout@v2
    - run: cd ../..
    - run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Stop containers
    - uses: actions/checkout@v2
    - run: docker-compose -f "docker-compose.yml" down
