name: GitHub CI

on:
  push:
    branches: [ master ]

jobs:
  Test:
    uses: ./.github/workflows/TEST.yml
  Sast:
    uses: ./.github/workflows/SAST.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  ContainerScanSecurity:
    uses: ./.github/workflows/container-scan-security.yml
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IaC:
    needs: [Sast, Test, ContainerScanSecurity]
    uses: ./.github/workflows/iac.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  Deploy:
    needs: [Sast, Test, ContainerScanSecurity, IaC]
    uses: ./.github/workflows/deploy.yml
    secrets:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GCR_EMAIL_ACCOUNT: ${{ secrets.GCR_EMAIL_ACCOUNT }}
      GCR_DEVOPS_SERVICE_ACCOUNT_KEY: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
      REGION: ${{ secrets.REGION }}