name: SAST workflow

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - id: Start mongo
        run: docker-compose -f docker-compose.yml up -d mongo
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - id: Compile
      - run: npm ci
      - id: Test
      - run: npm test
      - id: Down mongo
      - run: docker-compose -f docker-compose.yml down
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}