name: Test workflow

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: Test
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: docker-compose -f docker-compose.yml up -d mongo
      - run: npm test
      - run: docker-compose -f docker-compose.yml down